import { Instrument_Sans } from "next/font/google";
import "../../app/globals.css";
import { AuthProvider } from "../providers/Providers";

const sans = Instrument_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
