import { Instrument_Sans } from "next/font/google";
import "../../app/globals.css";
import Nav from "@/components/nav/Nav";

const sans = Instrument_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans.className}>

        <Nav />
        <main className="m-4">{children}</main>
      </body>
    </html>
  );
}
